#Slide Puzzle
#By project 3 of LNMIIT-CSI Branch

#Code begins here

import pygame , sys, random
from pygame.locals import *

#creating all the constants and local veriables
BOARD_WIDTH=4 
BOARD_HEIGHT=4
TILE_SIZE=80
WINDOW_WIDTH=640
WINDOW_HEIGHT=480
FPS=30
BLACK=NONE

# RED GREEN BLUE
BLACK=(0,0,0)
WHITE=(255,255,255)
BRIGHTBLUE=(0,50,255)
DARKTURQUOISE=(3,54,73)
GREEN=(0,204,0)

BGCOLOR=DARKTURQUOISE
TILECOLOR=GREEN
TEXTCOLOR=WHITE
BORDERCOLOR=BRIGHTBLUE
BASICFONTSIZE=20

BUTTONCOLOR=WHITE
BOOTONEXTCOLOR=BLACK
MESSAGECOLOR=WHITE

XMARGIN=int((WINDOWWIDTH-(TILESIZE*BOARDWIDTH+(BOARDWIDTH-1)))/2)
YMARGIN=int((WINDOWWIDTH-(TILESIZE*BOARDHEIGHT+(BOARDHEIGHT-1)))/2)

UP='up'
DOWN='down'
LEFT='left'
RIGHT='right'

def main() :
	global FPSCLOCK , DI
